articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment', views.leave_comment, name='leave_comment'),
    path('create_article/', views.create_article, name='create_article'),
    path('create/', views.create, name='create'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('registration/', include('registration.urls')),

]

registration/urls.py
from django.urls import path
from . import views


app_name = 'registration'
urlpatterns = [
    path('', views.reg, name='reg'),
    path('create_account', views.create_account, name='create_account'),
    path('authorization', views.authorization, name='authorization')
]

articles/models.py
from django.db import models
import datetime
from django.utils import timezone


class Article(models.Model):
	article_title = models.CharField('название статьи', max_length=200)
	article_text = models.TextField('текст статьи')
	pub_date = models.DateTimeField('дата публикации')

	def __str__(self):
		return self.article_title

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days=8))

	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('имя автора', max_length = 50)
	comment_text = models.CharField('текст комментария', max_length = 200)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Article
from django.utils import timezone


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'list.html', {'latest_articles_list': latest_articles_list})


def create(request):
    return render(request, 'create_article.html')


def create_article(request):
    a = Article(article_title=request.POST['article_name'], article_text=request.POST['article_text'],
                pub_date=timezone.now())
    a.save()
    return detail(request, a.id)


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

articles/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <meta charset="UTF-8">
    <title>{% block title %}My site{% endblock %}</title>

</head>
<body>
<div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
        {% if latest_articles_list %}
        {% for a in latest_articles_list %}
        <div class="text-center whtie"><a class="w-100" href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
        </div>
        <br>
        {% endfor %}{% endif %}
    </div>
</div>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
<br>
<div class="container">
    {% block content %} Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, odio.{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>-->
</body>
</html>

articles/templates/create_article.html
{% extends 'base.html' %}
{% block title %} Last articles {% endblock %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main</title>
</head>
<body>

<form action="{% url 'articles:create_article' %}" method="POST">
    {% csrf_token %}
    <br>
    <input type="text" required placeholder="Введите название статьи" name="article_name"><br><br>
    <textarea name="article_text" required cols="30" rows="10"></textarea><br><br>
    <button class="btn btn-dark btn-outline-light" type="submit">Создать данную статью.=)</button>
</form>
</body>

{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>
{% if article.was_published_recently %}
<h3>Новая статья!!! Залетай скорее</h3>
{% endif %}

<hr>
{% if latest_comments_list %}

{% for c in latest_comments_list %}
<p>
    <strong>{{c.author_name}}</strong>
<p>{{c.comment_text}}</p>
</p>
{% endfor %}
{% else %}
Комментарии не найдены! Станьте первым!!! ;-)
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
    <button type="submit">Отправить комментарий</button>
</form>
{% endblock %}

articles/templates/list.html
{% extends 'base.html' %}
{% block title %} Last articles {% endblock %}
{% block content %}
{{user.login}}
{% if latest_articles_list %}
<div class="offset-1">
    <div class="row mb-2 text-center">
        {% for a in latest_articles_list %}
        <div class="card mb-4 shadow-sm mx-1 col-5 cont">
            <div class="card-header">
                <h4 class="my-0 fw-normal">{{a.article_title}}</a><br></h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li></li>
                </ul>
                <a href="{% url 'articles:detail' a.id %}">
                    <button type="button" class="w-100 btn btn-lg btn-outline-primary">подробнее</button>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>


</div>
{% else %}
Статьи не найдены ;-(
{% endif %}
<br>
<a class="btn btn-dark btn-outline-light" href="{% url 'articles:create' %}">Создать новую статью.</a>

{% endblock %}